name: Main
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.5.1-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Crystal shard cache
        uses: actions/cache@v1
        with:
          path: lib
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-shards-
      - name: Install dependencies
        run: shards install
      - name: Run ameba
        run: crystal lib/ameba/bin/ameba.cr
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: crystallang/crystal:1.5.1-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Crystal shard cache
        uses: actions/cache@v1
        with:
          path: lib
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-shards-
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
